name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/nckh
            git pull origin main
            cd be
            ./mvnw clean package -DskipTests
            pkill -f 'java -jar' || true
            nohup java -jar target/*.jar --server.port=3000 > ~/nckh/be/app.log 2>&1 &
          EOF
